### ISSUE TITLE
源码下载下来会报错，以前版本更新一下也有这个问题

### ISSUE THREAD

**Issue by memedahui** [vondear/RxTools#11]
Error:Could not find any matches for com.tencent.mm.opensdk:wechat-sdk-android-with-mta:latest.integration as no versions of com.tencent.mm.opensdk:wechat-sdk-android-with-mta are available.
Required by:
    RxTools-master:app:unspecified > RxTools-master:RxTools-library:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by vondear** [comment]
compile('com.github.vondear:RxTools:v1.7.0') {
        exclude group: 'com.tencent.mm.opensdk'
}

**Comment by vondear** [comment]
在源码中改成这样 compile 'com.tencent.mm.opensdk:wechat-sdk-android-with-mta:1.3.4'
