### ISSUE TITLE
加入build.gradle 报错

### ISSUE THREAD

**Issue by OpenSourceMIUI** [vondear/RxTools#27]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:design:26.0.0-alpha1] AndroidManifest.xml:27:9-38
  	is also present at [com.android.support:cardview-v7:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.

请问,这是什么问题? 百度搜的也不太清楚

**Comment by OpenSourceMIUI** [comment]
这个问题我解决了, 在app的build.gradle里更改buildToolsVersion和support:design  的包的版本号,跟作者RxTools-library  里的版本号一样就可以了!   

但是:  如果要适配Android  26怎么办呢? 请问作者?  这么好的工具集还是希望作者能够一直维护下去, 谢谢!

**Comment by vondear** [comment]
恩恩，意见非常不错，已经修正过来了
