### ISSUE TITLE
ActivityScanerCode返回偶尔闪退，原因是还在解码中， onPause中将handle设置null，解码后又调用getHandle()发送消息，报空指针！

### ISSUE THREAD

**Issue by qq1458740677** [vondear/RxTools#43]
ActivityScanerCode返回偶尔闪退，原因是还在解码中， onPause中将handle设置null，解码后又调用getHandle()发送消息，报空指针！

**Comment by vondear** [comment]
好的，谢谢告知，正在修复

**Comment by sher-loki** [comment]
+                if (handler == null) {
 +                    // 连续扫描，不发送此消息扫描一次结束后就不能再次扫描
 +                    handler.sendEmptyMessage(com.vondear.rxtools.R.id.restart_preview);
 +                }

hi there. 你这句改错了   有空就改一下吧。

**Comment by vondear** [comment]
已修复

**Comment by chenlong0525** [comment]
ActivityScanerCode返回偶尔闪退这个解决了没
