### ISSUE TITLE
一点小小建议

### ISSUE THREAD

**Issue by budou1994** [vondear/RxTools#45]
你好，近期使用您这个类库的确方便了许多，现在有一些小的建议，在使用您的Rxdialog时，想到了偷懒就直接使用您的RxDialogEditSureCancel以及RxDialogSureCancel，但是这两个dialog中都有一些小问题，就是没有给出那个logo的view，也许作者您是有自己的考虑的，就是想请教一下是否可以把上方logo的那个方法给出，不管大家需要隐藏还是更换自己项目logo，都是很有帮助的。谢谢作者提供的轮子，为我开发提供了很多帮助，再次感谢！ @vondear

**Comment by vondear** [comment]
好的，我已同意调整了这两个类，添加了getLogoView方法
