### ISSUE TITLE
维码扫描

### ISSUE THREAD

**Issue by wodewzl** [vondear/RxTools#5]
维码扫描，拿不到结果，没法处理，没啥用

**Comment by vondear** [comment]
[ActivityScanerCode.java](https://github.com/vondear/RxTools/blob/master/RxTools-library/src/main/java/com/vondear/rxtools/activity/ActivityScanerCode.java)

请看 第 426 行到 435 行。

**Comment by wodewzl** [comment]
我看到这个处理的位置了，这个类是库里的，我直接依赖的，没依赖源码，无法取到返回值，还有就是依赖你这个库后，二维码并不能使用，闪退，用其他的二维码第三方时就报jar冲突，好头疼，能否把你的libs路径改下，放在项目的根目录下，不要以这种新式    compile files('src/main/libs/zbardecoder.jar')
    compile files('src/main/libs/zxing.jar')引用

**Comment by wodewzl** [comment]
有时间处理下，谢谢，还是蛮喜欢里面的一些东西

**Comment by vondear** [comment]
我这个类的目的就是给个解析的例子，你可以借鉴一下里面的方法
